services:
  langgraph_qna:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    volumes:
      - ./src/langgraph_app:/src
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network
      
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - langgraph_qna

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: